In [108]:
import pandas as pd
import numpy as np

## Loan

In [2]:
loan = pd.read_csv("../data/raw/loan.csv", sep=";")
loan.head()

   loan_id  account_id    date  amount  duration  payments status
0     5314        1787  930705   96396        12    8033.0      B
1     5316        1801  930711  165960        36    4610.0      A
2     6863        9188  930728  127080        60    2118.0      A
3     5325        1843  930803  105804        36    2939.0      A
4     7240       11013  930906  274740        60    4579.0      A

In [19]:
print(loan.shape)
loan["status"].value_counts()
loan.duplicated().value_counts()   # verificar duplicados

(682, 7)

False    682
Name: count, dtype: int64

## Trans

In [32]:
trans =  pd.read_csv("../data/raw/trans.csv", sep= ";", dtype= {"bank": str})
trans.head()

,trans_id,account_id,date,type,operation,amount,balance,k_symbol,bank,account
0,695247,2378,930101,PRIJEM,VKLAD,700.0,700.0,NaN,NaN,NaN
1,171812,576,930101,PRIJEM,VKLAD,900.0,900.0,NaN,NaN,NaN
2,207264,704,930101,PRIJEM,VKLAD,1000.0,1000.0,NaN,NaN,NaN
3,1117247,3818,930101,PRIJEM,VKLAD,600.0,600.0,NaN,NaN,NaN
4,579373,1972,930102,PRIJEM,VKLAD,400.0,400.0,NaN,NaN,NaN

In [33]:
print(trans.shape)
trans.info()

(1056320, 10)
<class 'pandas.DataFrame'>
RangeIndex: 1056320 entries, 0 to 1056319
Data columns (total 10 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   trans_id    1056320 non-null  int64
 1   account_id  1056320 non-null  int64
 2   date        1056320 non-null  int64
 3   type        1056320 non-null  str
 4   operation   873206 non-null   str
 5   amount      1056320 non-null  float64
 6   balance     1056320 non-null  float64
 7   k_symbol    574439 non-null   str
 8   bank        273508 non-null   str
 9   account     295389 non-null   float64
dtypes: float64(3), int64(3), str(4)
memory usage: 80.6 MB

In [40]:
print(trans["type"].value_counts(dropna=False))
print(trans["operation"].value_counts(dropna=False))

type
VYDAJ     634571
PRIJEM    405083
VYBER      16666
Name: count, dtype: int64
operation
VYBER             434918
PREVOD NA UCET    208283
NaN               183114
VKLAD             156743
PREVOD Z UCTU      65226
VYBER KARTOU        8036
Name: count, dtype: int64

In [51]:
trans[trans["operation"].isna()]

,trans_id,account_id,date,type,operation,amount,balance,k_symbol,bank,account
137,3591421,1844,930131,PRIJEM,NaN,12.6,3754.6,UROK,NaN,NaN
138,3617490,2632,930131,PRIJEM,NaN,47.5,15411.5,UROK,NaN,NaN
139,3579543,1493,930131,PRIJEM,NaN,13.3,5222.3,UROK,NaN,NaN
140,3558798,866,930131,PRIJEM,NaN,37.1,13181.1,UROK,NaN,NaN
141,3453599,6473,930131,PRIJEM,NaN,17.0,21078.0,UROK,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1056315,3626622,2906,981231,PRIJEM,NaN,62.3,13729.4,UROK,NaN,NaN
1056316,3627616,2935,981231,PRIJEM,NaN,81.3,19544.9,UROK,NaN,NaN
1056317,3625403,2869,981231,PRIJEM,NaN,60.2,14638.2,UROK,NaN,NaN
1056318,3626683,2907,981231,PRIJEM,NaN,107.5,23453.0,UROK,NaN,NaN
1056319,3626540,2902,981231,PRIJEM,NaN,164.1,41642.9,UROK,NaN,NaN

In [55]:
print(trans[trans["operation"].isna()]["k_symbol"].value_counts(dropna=False))
trans[trans["operation"].isna()]["type"].value_counts(dropna=False)

k_symbol
UROK    183114
Name: count, dtype: int64

type
PRIJEM    183114
Name: count, dtype: int64

In [63]:
trans["k_symbol"].value_counts(dropna=False)

k_symbol
NaN            481881
UROK           183114
SLUZBY         155832
SIPO           118065
                53433
DUCHOD          30338
POJISTNE        18500
UVER            13580
SANKC. UROK      1577
Name: count, dtype: int64

In [ ]:
trans.isna().sum()   # Cuenta cuantos NaN hay por columnas

trans_id           0
account_id         0
date               0
type               0
operation     183114
amount             0
balance            0
k_symbol      481881
bank          782812
account       760931
dtype: int64

## Client

In [147]:
client = pd.read_csv("../data/raw/client.csv",sep=";")
print(client.shape)
client.head()

(5369, 3)

   client_id  birth_number  district_id
0          1        706213           18
1          2        450204            1
2          3        406009            1
3          4        561201            5
4          5        605703            5

In [148]:
mes = (client["birth_number"] // 100) % 100
mes.describe()

count    5369.000000
mean       31.154032
std        25.307357
min         1.000000
25%         6.000000
50%        12.000000
75%        57.000000
max        62.000000
Name: birth_number, dtype: float64

In [149]:
mes.value_counts().sort_index() # Verificamos que los datos y el mes nos da un dato interesante segun la documentacion y es que del 1 al 12 son masculinos y del 51 al 62 femenino

birth_number
1     233
2     236
3     218
4     223
5     246
6     217
7     239
8     232
9     209
10    231
11    216
12    224
51    221
52    192
53    209
54    225
55    221
56    195
57    226
58    238
59    260
60    235
61    210
62    213
Name: count, dtype: int64

In [150]:
client["sex"] = np.where(mes <13,"M","F")

In [151]:
client

      client_id  birth_number  district_id sex
0             1        706213           18   F
1             2        450204            1   M
2             3        406009            1   F
3             4        561201            5   M
4             5        605703            5   F
...         ...           ...          ...  ..
5364      13955        456030            1   F
5365      13956        430406            1   M
5366      13968        680413           61   M
5367      13971        626019           67   F
5368      13998        535812           74   F

[5369 rows x 4 columns]

In [152]:
client["sex"].value_counts()

sex
M    2724
F    2645
Name: count, dtype: int64